---
title: " Holobionte Cross Validation"
date: "`r Sys.Date()`"
params: 
  scenario: "microbiote"
  run: 1
output:
  html_document:
    code_folding: hide
    highlight: espresso
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library,  message=FALSE,fig.width=10,fig.height=6,warning=FALSE}


library(snpStats)
library(magrittr)
library(data.table)
library(dplyr)
library(tidyverse)
library(devtools)
library(FactoMineR)
library(utils)
library(BGLR)
library(bigsnpr)
library(knitr)
library(rmarkdown)
 theme_set( theme_classic())



```

```{r}
scenario <- params$scenario
run <- params$run
regime <- "CO"
```

[//]: # "Load the various chunks in the various files"
```{r readChunks,  warning=FALSE, message=FALSE}
scenario = params$scenario
WORKING_DIR   = "~/work/holobionte_wp2/code/"

#PATH ##########################################################################

path_pheno = "../data/Vanille_Deru/donnees_pheno/"
path_OTU = "../data/Vanille_Deru/donnees_microbiote/"
path_output = "../data/Vanille_Deru/simulation/" 
path_geno =  "../data/Vanille_Deru/donnees_geno/"
path_RDS = paste0("../data/RDS/",scenario,"/",as.character(run),"/")
 
path_simu = path_output
# folder containing snp and otu data
data1 = "../data/Pérez/" #PEREZ
data2 = "../data/Vanille_Deru/simulation/" # VANILLE DERU


 ### Define working folder (contains R/Rmd file for current sample, parent contains global project files)

analysisParamsFilePath = file.path( WORKING_DIR, "Params.R")


paramsEnv = new.env();
source(analysisParamsFilePath, local = paramsEnv);

source( file.path( WORKING_DIR, "Load_parameter.R"));
source("Params.R")
source("Simubiome.R")

read_chunk( path=file.path( WORKING_DIR,"CV.R"))
read_chunk( path=file.path( WORKING_DIR,"Simuscript.R"))


```



### Environment  {.tabset}

#### Parameters 

<center>
```{r runInfo,  message=FALSE}

showSimpleDT( paramsEnv)
```



#### R

```{r runInfo_r,  message=FALSE}
print( sessionInfo());

```


### Modelisation

``` {r CV, warning=FALSE, message=FALSE,warning=FALSE,fig.width=15,fig.height=15, results='asis'} 

## @knitr CV
load(paste0(path_RDS,'simubiome.Rdata'))



#--> scale and transpose data
y = scale(s$y)

G_all = list()
B_all = list()
A_all = list()
D_all = list()
for (fold in 1:10) {
G_all[[fold]] = readRDS(paste0(path_RDS,"g_",regime,"_",fold,".RDS"))
B_all[[fold]] = readRDS(paste0(path_RDS,"b_",regime,"_",fold,".RDS"))
A_all[[fold]] = readRDS(paste0(path_RDS,"a_",regime,"_",fold,".RDS"))

if (file.exists(paste0(path_RDS,"g_",regime,"_",fold,".RDS"))) {
  G_all[[fold]] = readRDS(paste0(path_RDS,"g_",regime,"_",fold,".RDS"))
} else {
  G_all[[fold]] = NULL
}

if (file.exists(paste0(path_RDS,"b_",regime,"_",fold,".RDS"))) {
  B_all[[fold]] = readRDS(paste0(path_RDS,"b_",regime,"_",fold,".RDS"))
} else {
  B_all[[fold]] = NULL
  
}

if (file.exists(paste0(path_RDS,"a_",regime,"_",fold,".RDS"))) {
  A_all[[fold]] = readRDS(paste0(path_RDS,"a_",regime,"_",fold,".RDS"))
} else {
  A_all[[fold]] = NULL}



}


for (fold in 1:2) {
  D_all[[fold]] = readRDS(paste0(path_RDS,"d_",regime,"_",fold,".RDS"))
}

df<- list()
df_A =list()


for (CV in c("G","B","A")) {
  cors_gb <- c()
  cors_g <- c()
  cors_b <- c()
  Acors_gb <- c()
  Acors_g <- c()
  Acors_b <- c()
  all <- get(paste0(CV,"_all"))
  for (cluster in 1:10) {
    if (is.null(all[[cluster]]) == TRUE) {
    tst <- all[[cluster]]$tst
    cor_gb <- cor(all[[cluster]]$fm_Ggb$fm$yHat[tst],y[tst])
    cor_g <- cor(all[[cluster]]$fm_Gg$fm$yHat[tst],y[tst])
    cor_b <- cor(all[[cluster]]$fm_Gb$fm$yHat[tst],y[tst])
    Acor_gb <- cor(all[[cluster]]$fm_Ggb$fm$yHat[-tst],y[-tst])
    Acor_g <- cor(all[[cluster]]$fm_Gg$fm$yHat[-tst],y[-tst])
    Acor_b <- cor(all[[cluster]]$fm_Gb$fm$yHat[-tst],y[-tst])
    Acors_gb <- append(Acors_gb, Acor_gb) 
    Acors_g <- append(Acors_g, Acor_g) 
    Acors_b <- append(Acors_b, Acor_b) 
    cors_gb <- append(cors_gb, cor_gb) 
    cors_g <- append(cors_g, cor_g) 
    cors_b <- append(cors_b, cor_b) 
    
  }
  
  df[[CV]] <- data.frame("GB" = cors_gb,"G" = cors_g,"B" = cors_b)
  df_A[[CV]] <- data.frame("GB" = Acors_gb,"G" = Acors_g,"B" = Acors_b)


}

}



for (CV in c("D")) {
  cors_gb <- c()
  cors_g <- c()
  cors_b <- c()
  Acors_gb <- c()
  Acors_g <- c()
  Acors_b <- c()
  all <- get(paste0(CV,"_all"))
  for (cluster in 1:2) {
    tst <- all[[cluster]]$tst
    cor_gb <- cor(all[[cluster]]$fm_Ggb$fm$yHat[tst],y[tst])
    cor_g <- cor(all[[cluster]]$fm_Gg$fm$yHat[tst],y[tst])
    cor_b <- cor(all[[cluster]]$fm_Gb$fm$yHat[tst],y[tst])
    Acor_gb <- cor(all[[cluster]]$fm_Ggb$fm$yHat[-tst],y[-tst])
    Acor_g <- cor(all[[cluster]]$fm_Gg$fm$yHat[-tst],y[-tst])
    Acor_b <- cor(all[[cluster]]$fm_Gb$fm$yHat[-tst],y[-tst])
    Acors_gb <- append(Acors_gb, Acor_gb) 
    Acors_g <- append(Acors_g, Acor_g) 
    Acors_b <- append(Acors_b, Acor_b) 
    cors_gb <- append(cors_gb, cor_gb) 
    cors_g <- append(cors_g, cor_g) 
    cors_b <- append(cors_b, cor_b) 
    
  }
  
  df[[CV]] <- data.frame("GB" = cors_gb,"G" = cors_g,"B" = cors_b)
  df_A[[CV]] <- data.frame("GB" = Acors_gb,"G" = Acors_g,"B" = Acors_b)
  
  
}





write.csv(df,paste0(path_RDS,"df_corr"))
write.csv(df_A,paste0(path_RDS,"df_corr_a"))

# Melt the data frame into long format
Matrice <- melt(df)
colnames(Matrice) = c("Model","corr","CV")
Matrice_A <- melt(df_A)
colnames(Matrice_A) = c("Model","corr","CV")


saveRDS(Matrice,paste0(path_RDS,"df_corr.RDS"))
saveRDS(Matrice_A,paste0(path_RDS,"df_corr_a.RDS"))


boxplot(df$G, horizontal = TRUE, col = c("darkorange", "deepskyblue", "forestgreen"), 
        main = "Correlation des valeurs prédite par l'apprentissage sur un cluster génétique", 
        xlab = "Correlations")

boxplot(df$B, horizontal = TRUE, col = c("darkorange", "deepskyblue", "forestgreen"), 
        main = "Correlation des valeurs prédite par l'apprentissage sur un cluster microbien", 
        xlab = "Correlations")

boxplot(df$A, horizontal = TRUE, col = c("darkorange", "deepskyblue", "forestgreen"), 
        main = "Correlation des valeurs prédite par l'apprentissage sur un cluster aléatoire", 
        xlab = "Correlations")




ggplot(Matrice) + geom_boxplot(aes(x = corr, y = CV)) + facet_grid(Matrice$Model)




ggplot(Matrice_A) + geom_boxplot(aes(x = corr, y = CV)) + facet_grid(Matrice_A$Model)


```
